import { expect, test, type Page, type Route } from '@playwright/test'

const json = (body: unknown, status = 200) => ({ status, contentType: 'application/json', body: JSON.stringify(body) })

async function mockApi(page: Page, quickBodies: unknown[] = []) {
  await page.route('**/api/**', async (route: Route) => {
    const url = route.request().url(); const method = route.request().method(); const path = new URL(url).pathname
    if (path.endsWith('/users/login')) return route.fulfill(json({ access_token: 'aaa.bbb.ccc', user: { id: 1, username: 'admin', full_name: '管理员', role: 'admin', is_active: true } }))
    if (path.endsWith('/users/me')) return route.fulfill(json({ id: 1, username: 'admin', full_name: '管理员', role: 'admin', is_active: true }))
    if (path.endsWith('/menu')) return route.fulfill(json({ schema_version: 2, role: 'admin', default_home: 'dashboard', groups: [{ id: 'quality', label: '质控' }, { id: 'governance', label: '治理' }, { id: 'system', label: '系统' }], menu: [{ id: 'dashboard', label: '工作台', group: 'quality', route_name: 'workbench' }, { id: 'patient-qc', label: '患者质控', group: 'quality', route_name: 'quality-patients' }, { id: 'audit', label: '质控记录', group: 'quality', route_name: 'quality-records' }, { id: 'relay', label: '告警推送配置', group: 'governance', route_name: 'governance-relay' }, { id: 'access', label: '用户与权限', group: 'system', route_name: 'system-access' }, { id: 'push-progress', label: '任务进度', group: 'system', route_name: 'tasks-progress' }] }))
    if (path.endsWith('/patient-qc/patients')) return route.fulfill(json({ total: 1, items: [{ patient_id: 'P-1', visit_number: '1', patient_name: '测试患者', admission_no: 'A-1', dept: '测试科', discharge_dept_name: '测试科', highest_severity: 'high', high_count: 1, medium_count: 0, issue_count: 1, pending_count: 1, resolved_count: 0, audit_type_count: 1, push_log_count: 1, latest_push_time: '2026-08-01 10:00:00' }] }))
    if (path.endsWith('/patient-qc/patient-detail')) return route.fulfill(json({ patient: { patient_id: 'P-1', visit_number: '1', patient_name: '测试患者', admission_no: 'A-1', dept: '测试科', discharge_main_diagnosis: '肺炎主诊断' }, summary: { audit_type_count: 1, push_log_count: 1, issue_count: 1, high_count: 1, medium_count: 0, pending_count: 1, resolved_count: 0 }, audit_groups: [{ audit_type_code: 'demo', audit_type_name: '演示质控', severity: 'high', logs: [{ push_log_id: 77, push_time: '2026-08-01 10:00:00', status: 'success', severity: 'high', feedback: { status: 'pending', feedback_text: '待处理', assigned_to_name: '张医生' }, dimensions: [{ dimension_name: '病历完整性', status: 'fail', severity: 'high', issue_summary: '缺少记录', explanation: '需补充', recommendation: '及时完善', medical_evidence: [{ text: '病历证据' }], nursing_evidence: { text: '护理证据' } }] }] }] }))
    if (path.endsWith('/patient-qc/feedback/quick-action')) { quickBodies.push(JSON.parse(route.request().postData() || '{}')); return route.fulfill(json({ message: 'ok' })) }
    if (path.endsWith('/patient-qc/export/patient-visit-summary')) {
      return route.fulfill({
        status: 200,
        contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        headers: { 'content-disposition': 'attachment; filename=patient_visit_summary_mock.xlsx' },
        body: Buffer.from('mock-xlsx'),
      })
    }
    if (path.endsWith('/push/tasks/latest')) return route.fulfill(json({ task_id: 'task-1', status: 'running', total: 4, processed: 1, success: 1, failed: 0, skipped: 0 }))
    if (path.endsWith('/scheduler/history')) { const failed = new URL(url).searchParams.get('status') === 'failed'; return route.fulfill(json({ total: 1, items: [{ id: 31, status: failed ? 'failed' : 'completed', trigger_type: 'auto', run_time: '2026-08-11 08:00:00', query_date: '2026-08-10', audit_type_code: 'progress_vs_nursing', audit_run_mode: 'daily_increment', total_records: 4, success_count: failed ? 2 : 4, failed_count: failed ? 2 : 0, duration_seconds: 12, error_msg: failed ? 'mock failure' : '' }] })) }
    if (path === '/api/logs' || path === '/api/logs/') return route.fulfill(json({ total: 1, items: [{ id: 88, patient_id: 'P-1', patient_name: '高风险患者', dept: '测试科', severity: 'high', status: 'success', inconsistency: 1, risk_score: 95, push_time: '2026-08-11 10:00:00' }] }))
    if (path.endsWith('/logs/88')) return route.fulfill(json({ id: 88, patient_id: 'P-1', patient_name: '高风险患者', severity: 'high', status: 'success', audit_result: { dimensions: [] } }))
    if (path.endsWith('/logs')) return route.fulfill(json({ total: 1, items: [{ id: 88, patient_id: 'P-1', patient_name: '高风险患者', dept: '测试科', severity: 'high', status: 'success', inconsistency: 1, risk_score: 95, push_time: '2026-08-11 10:00:00' }] }))
    if (path.endsWith('/config/relay-alert')) return route.fulfill(json({ enabled: true, base_url: 'http://relay.local', endpoint: '/qc-record-alert', source: '测试', severity_levels: ['high'], alert_dept_filter: [], secret_key_masked: '***' }))
    if (path.endsWith('/relay/receiver-config')) return route.fulfill(json({ receiver_rules: { high: { attending_doctor: true, record_creator: true, nurse_head: true, fixed_users: [], dedupe: true, max_receivers: 5 }, medium: { attending_doctor: true, record_creator: true, nurse_head: false, fixed_users: [], dedupe: true, max_receivers: 3 }, low: { attending_doctor: false, record_creator: false, nurse_head: false, fixed_users: [], dedupe: true, max_receivers: 0 } } }))
    if (path.endsWith('/relay/preview-receivers')) { quickBodies.push(JSON.parse(route.request().postData() || '{}')); return route.fulfill(json({ receivers: [{ source: 'attending_doctor', userid: 'u1', user_name: '张医生' }], receiver_debug: { deduped: 1, skipped: [] }, rule: 'high' })) }
    if (path.endsWith('/relay/receiver-rules')) { quickBodies.push(JSON.parse(route.request().postData() || '{}')); return route.fulfill(json({ rules: { high: {}, medium: {}, low: {} } })) }
    if (path.endsWith('/relay/search-user')) return route.fulfill(json({ results: [] }))
    if (path.endsWith('/users')) return route.fulfill(json({ total: 1, items: [{ id: 1, username: 'admin', full_name: '管理员', role: 'admin', is_active: true }] }))
    if (path.endsWith('/roles/menus/catalog')) return route.fulfill(json([{ id: 'dashboard', label: '工作台' }]))
    if (path.includes('/roles') && method === 'GET' && !path.includes('/menus')) return route.fulfill(json([{ id: 2, name: 'admin', description: '管理员', permissions: [], menus: [], departments: [] }]))
    if (path.endsWith('/roles')) return route.fulfill(json([{ id: 2, name: 'admin', description: '管理员', permissions: [], menus: [], departments: [] }]))
    if (path.endsWith('/permissions')) return route.fulfill(json([{ id: 11, name: 'view_patient', description: '查看患者', module: 'quality' }]))
    if (path.endsWith('/departments')) return route.fulfill(json([{ id: 3, name: '测试科', code: 'D1', manager_id: null }]))
    if (path.endsWith('/roles/2/permissions/11') && method === 'POST') { quickBodies.push({ path, body: JSON.parse(route.request().postData() || '{}') }); return route.fulfill(json({ message: 'ok' })) }
    if (method === 'GET') return route.fulfill(json({ items: [], total: 0 }))
    return route.fulfill(json({ message: 'ok' }))
  })
}

async function login(page: Page, bodies: unknown[]) { await mockApi(page, bodies); await page.goto('./#/login'); await page.getByPlaceholder('请输入用户名').fill('admin'); await page.getByPlaceholder('请输入密码').fill('password'); await page.getByRole('button', { name: '登录' }).click(); await expect(page.locator('.app-shell')).toBeVisible() }
async function assertViewport(page: Page, project: string) { if (project === 'mobile-390') expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true) }

test.describe('functional migration', () => {
  test('PatientQc真实详情、快捷动作与响应式', async ({ page }, info) => { const bodies: unknown[] = []; const listUrls: string[] = []; page.on('request', (request) => { if (request.url().includes('/api/patient-qc/patients')) listUrls.push(request.url()) }); await login(page, bodies); await page.goto('./#/quality/patients?source=workbench&severity=high'); await expect(page.getByText('来自工作台的联动筛选')).toBeVisible(); await expect.poll(() => listUrls.some((url) => url.includes('severity=high'))).toBe(true); const linkedUrl = listUrls.find((url) => url.includes('severity=high')) as string; expect(linkedUrl).not.toContain('source=workbench'); await expect(page.getByRole('cell', { name: /测试患者/ })).toBeVisible(); await page.getByRole('button', { name: '详情', exact: true }).click(); await page.getByRole('button', { name: '患者信息' }).click(); await expect(page.getByText('肺炎主诊断')).toBeVisible(); await expect(page.getByText('待处理', { exact: true }).first()).toBeVisible(); await page.getByRole('button', { name: '维度问题' }).click(); await expect(page.locator('.dim-name', { hasText: '病历完整性' })).toBeVisible(); await expect(page.locator('.dim-issue', { hasText: '缺少记录' })).toBeVisible(); await page.getByRole('button', { name: '推送记录' }).click(); await page.getByRole('button', { name: '已整改' }).click(); await page.getByRole('button', { name: /确定|确认/ }).last().click(); await expect.poll(() => bodies).toContainEqual({ push_log_id: 77, action: 'rectified' }); await assertViewport(page, info.project.name) })
  test('PatientQc导出携带当前筛选且不含分页元信息', async ({ page }, info) => {
    const exportUrls: string[] = []
    await login(page, [])
    page.on('request', (request) => {
      if (request.url().includes('/patient-qc/export/patient-visit-summary')) exportUrls.push(request.url())
    })
    await page.goto('./#/quality/patients?source=workbench&severity=high&dept=%E6%B5%8B%E8%AF%95%E7%A7%91')
    await expect(page.getByRole('cell', { name: /测试患者/ })).toBeVisible()
    const exportBtn = page.getByRole('button', { name: '导出汇总' })
    await expect(exportBtn).toBeEnabled()
    await exportBtn.click()
    await page.getByRole('menuitem', { name: /导出病历数据/ }).click()
    await expect(page.getByText(/将导出当前筛选条件下全部 1 位患者的完整临床文书汇总/)).toBeVisible()
    await page.getByRole('button', { name: /确定|确认/ }).last().click()
    await expect.poll(() => exportUrls.length).toBeGreaterThan(0)
    const exportUrl = exportUrls[exportUrls.length - 1]
    const params = new URL(exportUrl).searchParams
    expect(params.get('severity')).toBe('high')
    expect(params.get('dept')).toBe('测试科')
    expect(params.has('page')).toBe(false)
    expect(params.has('limit')).toBe(false)
    expect(params.has('source')).toBe(false)
    expect(params.has('log_id')).toBe(false)
    await assertViewport(page, info.project.name)
  })
  test('Relay规则、预览与响应式', async ({ page }, info) => { const bodies: unknown[] = []; await login(page, bodies); await page.goto('./#/governance/relay'); await expect(page.getByText('high 接收规则')).toBeVisible(); await page.getByPlaceholder('正整数 push_log_id').fill('88'); await page.getByRole('button', { name: '查询预览' }).click(); await expect.poll(() => bodies).toContainEqual({ push_log_id: 88, severity: 'high' }); await expect(page.getByText('张医生')).toBeVisible(); await page.getByRole('button', { name: '保存接收规则' }).click(); await page.getByRole('button', { name: /确定|确认/ }).last().click(); await expect.poll(() => bodies.some((b: any) => b.rules && Object.keys(b).length === 1 && b.rules.high && b.rules.medium && b.rules.low)).toBe(true); await assertViewport(page, info.project.name) })
  test('Access角色授权与响应式', async ({ page }, info) => { const bodies: unknown[] = []; await login(page, bodies); await page.goto('./#/system/access'); await expect(page.getByText('admin', { exact: true }).first()).toBeVisible(); await expect(page.locator('.el-loading-mask')).toBeHidden(); const preexistingDialog = page.locator('.el-overlay-dialog:visible'); if (await preexistingDialog.count()) await preexistingDialog.getByRole('button').first().click(); const railRole = page.locator('.rail button').filter({ hasText: /^角色授权$/ }); await expect(railRole).toBeVisible(); await railRole.click(); await expect(page.locator('main h2', { hasText: '角色授权' })).toBeVisible(); const select = page.locator('.el-select__wrapper:visible'); await expect(select).toBeVisible(); await select.click(); await page.getByRole('option', { name: 'admin', exact: true }).click(); await expect(page.locator('main .el-card__header').filter({ hasText: '权限' })).toBeVisible(); await expect(page.locator('main .el-card__header').filter({ hasText: '菜单' })).toBeVisible(); await expect(page.locator('main .el-card__header').filter({ hasText: '科室' })).toBeVisible(); await page.getByText('view_patient', { exact: true }).click(); await page.getByRole('button', { name: /确定|确认/ }).last().click(); await expect.poll(() => bodies).toContainEqual({ path: '/api/roles/2/permissions/11', body: {} }); await assertViewport(page, info.project.name) })
  test('Workbench高风险事件联动到指定详情', async ({ page }, info) => { test.skip(info.project.name !== 'desktop-1366', '高风险联动至少在桌面项目验证'); const bodies: unknown[] = []; const detailRequests: string[] = []; const listRequests: string[] = []; await login(page, bodies); page.on('request', (request) => { const url = new URL(request.url()); if (url.pathname.endsWith('/api/logs/88')) detailRequests.push(request.url()); if (url.pathname.endsWith('/api/logs')) listRequests.push(request.url()) }); await page.goto('./#/workbench'); const event = page.getByRole('button', { name: /高风险事件：/ }).first(); await expect(event).toBeVisible(); await expect(event).toHaveAttribute('aria-label', /高风险事件/); await event.focus(); await event.press('Enter'); await expect(page).toHaveURL(/source=workbench/); await expect(page).toHaveURL(/log_id=88/); await expect(page).toHaveURL(/patient_id=P-1/); await expect(page).toHaveURL(/alert_level=red/); await expect.poll(() => detailRequests.length).toBeGreaterThan(0); const linkedList = listRequests[listRequests.length - 1] || ''; expect(linkedList).not.toContain('source=workbench'); expect(linkedList).not.toContain('log_id=88'); await expect(page.getByText('质控记录详情')).toBeVisible() })
  test('任务进度使用 processed 并导航任务质控日期', async ({ page }, info) => { test.skip(info.project.name !== 'desktop-1366', '任务进度契约至少在桌面项目验证'); const historyUrls: string[] = []; const logUrls: string[] = []; await login(page, []); page.on('request', (request) => { if (request.url().includes('/api/scheduler/history')) historyUrls.push(request.url()); if (new URL(request.url()).pathname.endsWith('/api/logs')) logUrls.push(request.url()) }); await page.goto('./#/tasks/progress'); await expect(page.getByText('1 / 4')).toBeVisible(); await expect.poll(() => historyUrls.length).toBeGreaterThan(0); await page.locator('.filters .el-select').first().click(); await page.getByRole('option', { name: '失败' }).click(); await page.getByRole('button', { name: '查询' }).click(); await expect.poll(() => historyUrls.some((url) => url.includes('status=failed'))).toBe(true); await page.getByRole('button', { name: '重置' }).click(); await page.getByRole('button', { name: '查看质控记录' }).click(); await expect(page).toHaveURL(/source=task-progress/); await expect(page).toHaveURL(/date_from=2026-08-10/); await expect(page).toHaveURL(/date_to=2026-08-10/); await expect(page).toHaveURL(/audit_type_code=progress_vs_nursing/); await expect.poll(() => logUrls.some((url) => url.includes('date_from=2026-08-10') && url.includes('date_to=2026-08-10'))).toBe(true); expect(logUrls.find((url) => url.includes('date_from=2026-08-10'))).not.toContain('source=task-progress'); })
  test('Audit记录独立详情入口', async ({ page }, info) => { test.skip(info.project.name !== 'desktop-1366', '独立详情至少在桌面项目验证'); await page.addInitScript(() => { const opened: unknown[] = []; (window as any).__opened = opened; window.open = ((url: string, target: string, features: string) => { opened.push({ url, target, features }); return null }) as any }); await login(page, []); await page.goto('./#/quality/records'); await expect(page.getByText('高风险患者')).toBeVisible(); await page.getByRole('button', { name: '更多' }).first().click(); await page.getByRole('menuitem', { name: '推送详情（JSON）' }).click(); const opened = await page.evaluate(() => (window as any).__opened); expect(opened[0]).toMatchObject({ url: '/log_detail.html?id=88', target: '_blank' }); expect(opened[0].features).toContain('noopener') })
})
