-- 039 规则中心六表（Oracle 生产应用库）
-- 红线：本脚本随代码交付但【不自动执行】；由 DBA 按 023 §9.1 批准单流程手工执行。
-- 空串语义：Oracle 中 '' 等于 NULL——所有字符串列不设 DEFAULT ''，插入由应用层显式提供值。
-- ID 策略：应用侧 uuid4().hex[:32] 字符串主键，无序列无触发器。
-- CLOB 列置于表尾规避 ORA-24816（CLOB 与其他列混插时报错）。

CREATE TABLE MED_PREARCHIVE_RULE_VERSION (
    ID                  VARCHAR2(32)   NOT NULL,
    RULE_KEY            VARCHAR2(128)  NOT NULL,
    DOMAIN              VARCHAR2(32)   DEFAULT 'medical_record' NOT NULL,
    TRACK               VARCHAR2(32)   DEFAULT 'main' NOT NULL,
    ORIGIN              VARCHAR2(64)   DEFAULT 'manual' NOT NULL,
    RULE_VERSION        VARCHAR2(64)   NOT NULL,
    SET_VERSION         VARCHAR2(64)   NOT NULL,
    STATUS              VARCHAR2(16)   DEFAULT 'draft' NOT NULL,
    CONTENT_SHA256      VARCHAR2(64)   NOT NULL,
    DRAFT_EDIT_VERSION  NUMBER(10)     DEFAULT 1 NOT NULL,
    BASED_ON_VERSION    VARCHAR2(64)   NOT NULL,
    APPROVED_BY         VARCHAR2(128)  NOT NULL,
    APPROVED_AT         DATE,
    PUBLISHED_AT        DATE,
    RETIRED_AT          DATE,
    CREATED_BY          VARCHAR2(128)  NOT NULL,
    CREATED_AT          DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT          DATE           DEFAULT SYSDATE NOT NULL,
    CONTENT_JSON        CLOB           NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_RULE_VERSION PRIMARY KEY (ID),
    CONSTRAINT UQ_PREARCHIVE_RULE_KEY_VERSION UNIQUE (RULE_KEY, RULE_VERSION),
    CONSTRAINT CK_PREARCHIVE_RULE_STATUS CHECK (STATUS IN
        ('draft','validated','approved','published','retired'))
);

COMMENT ON TABLE  MED_PREARCHIVE_RULE_VERSION IS '039 规则中心：不可变规则版本（draft 可编辑，validated+ 冻结）';
COMMENT ON COLUMN MED_PREARCHIVE_RULE_VERSION.RULE_KEY IS '规则业务键（=DSL rule_id），跨文件不得重复';
COMMENT ON COLUMN MED_PREARCHIVE_RULE_VERSION.SET_VERSION IS '所属规则集快照版本（文件导入=文件 version）';
COMMENT ON COLUMN MED_PREARCHIVE_RULE_VERSION.CONTENT_SHA256 IS 'canonical JSON SHA-256（排序键+无空白）';

CREATE INDEX IX_PREARCHIVE_RULE_KEY_STATUS ON MED_PREARCHIVE_RULE_VERSION (RULE_KEY, STATUS);
CREATE INDEX IX_PREARCH_RULE_DOMAIN_TRACK ON MED_PREARCHIVE_RULE_VERSION (DOMAIN, TRACK);

CREATE TABLE MED_PREARCHIVE_RULE_POINTER (
    ID                  VARCHAR2(32)   NOT NULL,
    DOMAIN              VARCHAR2(32)   NOT NULL,
    TRACK               VARCHAR2(32)   DEFAULT 'main' NOT NULL,
    RULE_KEY            VARCHAR2(128)  NOT NULL,
    PUBLISHED_VERSION   VARCHAR2(64)   NOT NULL,
    POINTER_VERSION     NUMBER(10)     DEFAULT 1 NOT NULL,
    UPDATED_BY          VARCHAR2(128)  NOT NULL,
    UPDATED_AT          DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_RULE_POINTER PRIMARY KEY (ID),
    CONSTRAINT UQ_PREARCHIVE_RULE_POINTER UNIQUE (DOMAIN, TRACK, RULE_KEY)
);

COMMENT ON TABLE MED_PREARCHIVE_RULE_POINTER IS '039 规则中心：发布指针（registry 模式运行时唯一读取入口；乐观号防并发覆盖）';

CREATE TABLE MED_PREARCHIVE_RULE_AUDIT (
    ID                  VARCHAR2(32)   NOT NULL,
    ACTION              VARCHAR2(32)   NOT NULL,
    RULE_KEY            VARCHAR2(128)  NOT NULL,
    VERSION_FROM        VARCHAR2(64)   NOT NULL,
    VERSION_TO          VARCHAR2(64)   NOT NULL,
    ACTOR_ID            VARCHAR2(128)  NOT NULL,
    ACTOR_NAME          VARCHAR2(128)  NOT NULL,
    REASON              VARCHAR2(512)  NOT NULL,
    REQUEST_ID          VARCHAR2(64)   NOT NULL,
    CREATED_AT          DATE           DEFAULT SYSDATE NOT NULL,
    DETAIL_JSON         CLOB           NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_RULE_AUDIT PRIMARY KEY (ID),
    CONSTRAINT CK_PREARCHIVE_AUDIT_ACTION CHECK (ACTION IN
        ('create_draft','update_draft','validate','approve','reject','publish',
         'rollback','retire','import','config_update','outbox_retry','contract_test'))
);

COMMENT ON TABLE  MED_PREARCHIVE_RULE_AUDIT IS '039 规则中心：管理审计（append-only，应用层禁 UPDATE/DELETE）';

CREATE INDEX IX_PREARCHIVE_RULE_AUDIT_KEY ON MED_PREARCHIVE_RULE_AUDIT (RULE_KEY, CREATED_AT);
CREATE INDEX IX_PREARCHIVE_RULE_AUDIT_TIME ON MED_PREARCHIVE_RULE_AUDIT (CREATED_AT);

CREATE TABLE MED_PREARCHIVE_DESTINATION (
    CODE                        VARCHAR2(64)   NOT NULL,
    KIND                        VARCHAR2(16)   DEFAULT 'emr' NOT NULL,
    ENABLED                     NUMBER(1)      DEFAULT 0 NOT NULL,
    BASE_URL                    VARCHAR2(512)  NOT NULL,
    ENDPOINT                    VARCHAR2(255)  NOT NULL,
    AUTH_TYPE                   VARCHAR2(32)   DEFAULT 'hmac_sha256' NOT NULL,
    SECRET_REF                  VARCHAR2(255)  NOT NULL,
    SCHEMA_VERSION              VARCHAR2(16)   DEFAULT '1.0.0' NOT NULL,
    TIMEOUT_SECONDS             NUMBER(10)     DEFAULT 5 NOT NULL,
    MAX_ATTEMPTS                NUMBER(10)     DEFAULT 6 NOT NULL,
    ALLOW_INSECURE_INTERNAL_HTTP NUMBER(1)     DEFAULT 0 NOT NULL,
    CONFIG_VERSION              NUMBER(10)     DEFAULT 1 NOT NULL,
    UPDATED_BY                  VARCHAR2(128)  NOT NULL,
    UPDATED_AT                  DATE           DEFAULT SYSDATE NOT NULL,
    CREATED_AT                  DATE           DEFAULT SYSDATE NOT NULL,
    SEND_SEVERITIES_JSON        CLOB           NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_DESTINATION PRIMARY KEY (CODE),
    CONSTRAINT CK_PREARCHIVE_DEST_KIND CHECK (KIND IN ('emr','his','mock')),
    CONSTRAINT CK_PREARCHIVE_DEST_AUTH CHECK (AUTH_TYPE IN ('hmac_sha256','mtls','none'))
);

COMMENT ON TABLE  MED_PREARCHIVE_DESTINATION IS '039 规则中心：投递目标配置（密钥只存 env 引用，永不落明文）';
COMMENT ON COLUMN MED_PREARCHIVE_DESTINATION.SECRET_REF IS 'env:VAR_NAME 形式的密钥引用；API/UI 永不回明文';

CREATE INDEX IX_PREARCHIVE_DEST_KIND ON MED_PREARCHIVE_DESTINATION (KIND);

CREATE TABLE MED_PREARCHIVE_OUTBOX (
    ID                  VARCHAR2(32)   NOT NULL,
    EVENT_ID            VARCHAR2(64)   NOT NULL,
    DESTINATION_CODE    VARCHAR2(64)   NOT NULL,
    IDEMPOTENCY_KEY     VARCHAR2(128)  NOT NULL,
    STATUS              VARCHAR2(16)   DEFAULT 'pending' NOT NULL,
    ATTEMPTS            NUMBER(10)     DEFAULT 0 NOT NULL,
    NEXT_RETRY_AT       DATE,
    LEASE_UNTIL         DATE,
    LEASE_OWNER         VARCHAR2(128)  NOT NULL,
    LAST_HTTP_STATUS    NUMBER(10),
    LAST_ERROR          VARCHAR2(512)  NOT NULL,
    CREATED_AT          DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_AT          DATE           DEFAULT SYSDATE NOT NULL,
    PAYLOAD_JSON        CLOB           NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_OUTBOX PRIMARY KEY (ID),
    CONSTRAINT UQ_PREARCHIVE_OUTBOX UNIQUE (EVENT_ID, DESTINATION_CODE),
    CONSTRAINT CK_PREARCHIVE_OUTBOX_STATUS CHECK (STATUS IN
        ('pending','sending','sent','retry','dead','disabled'))
);

COMMENT ON TABLE MED_PREARCHIVE_OUTBOX IS '039 规则中心：EMR/HIS 可靠投递 Outbox（每事件每目标一行）';

CREATE INDEX IX_PREARCHIVE_OUTBOX_STATUS ON MED_PREARCHIVE_OUTBOX (STATUS, NEXT_RETRY_AT);

CREATE TABLE MED_PREARCHIVE_DELIVERY_LOG (
    ID                  VARCHAR2(32)   NOT NULL,
    OUTBOX_ID           VARCHAR2(32)   NOT NULL,
    EVENT_ID            VARCHAR2(64)   NOT NULL,
    DESTINATION_CODE    VARCHAR2(64)   NOT NULL,
    ATTEMPT             NUMBER(10)     DEFAULT 1 NOT NULL,
    HTTP_STATUS         NUMBER(10),
    OUTCOME             VARCHAR2(16)   NOT NULL,
    ACK_EVENT_ID        VARCHAR2(64)   NOT NULL,
    RECEIVER_REFERENCE  VARCHAR2(255)  NOT NULL,
    DETAIL              VARCHAR2(512)  NOT NULL,
    CREATED_AT          DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_DELIVERY_LOG PRIMARY KEY (ID),
    CONSTRAINT CK_PREARCHIVE_DELIVERY_OUTCOME CHECK (OUTCOME IN
        ('sent','duplicate','retryable','terminal','unknown'))
);

COMMENT ON TABLE MED_PREARCHIVE_DELIVERY_LOG IS '039 规则中心：投递尝试日志（脱敏，append-only）';

CREATE INDEX IX_PREARCHIVE_DELIVERY_EVENT ON MED_PREARCHIVE_DELIVERY_LOG (EVENT_ID, DESTINATION_CODE);
CREATE INDEX IX_PREARCHIVE_DELIVERY_TIME ON MED_PREARCHIVE_DELIVERY_LOG (CREATED_AT);
