-- 046 闭环 10 表 + MED_PREARCHIVE_RESULT 4 列（Oracle 生产应用库）
-- 红线：本脚本随代码交付但【不自动执行】；由 DBA 按 023 §9.1 批准单流程手工执行。
-- 与 SQLite 侧 scripts/migrate_prearchive_schema_20260910.py 等价（列集合一致）。
-- 空串语义：Oracle 中 '' 等于 NULL——字符串列不设 DEFAULT ''，插入由应用层提供。
-- ID 策略：应用侧 uuid4().hex[:32] 字符串主键，无序列无触发器。
-- CLOB 列置于表尾规避 ORA-24816。


-- 评分目录快照行（每次导入一批；历史批次保留不覆盖）。
CREATE TABLE MED_PREARCHIVE_CATALOG_ITEM (
    ID                   VARCHAR2(32) NOT NULL,
    SOURCE_SYSTEM        VARCHAR2(64) NOT NULL,
    SNAPSHOT_ID          VARCHAR2(128) NOT NULL,
    FID                  NUMBER(10) NOT NULL,
    ORIGINAL_TEXT_SHA256 VARCHAR2(64) NOT NULL,
    SCORE                VARCHAR2(16) NOT NULL,
    GROUP_CODE           VARCHAR2(16) NOT NULL,
    GROUP_NAME           VARCHAR2(64) NOT NULL,
    ENABLED              NUMBER(10) DEFAULT 1 NOT NULL,
    COLLECTED_AT         DATE,
    IMPORTED_AT          DATE NOT NULL,
    IMPORTED_BY          VARCHAR2(128) NOT NULL,
    ORIGINAL_TEXT        CLOB NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_CATALOG_ITEM PRIMARY KEY (ID),
    CONSTRAINT UQ_PREARCHIVE_CATALOG_SNAP_FID UNIQUE (SNAPSHOT_ID, FID)
);
COMMENT ON TABLE MED_PREARCHIVE_CATALOG_ITEM IS '046 无纸化评分目录快照（92 条/批，历史保留）';
CREATE INDEX IX_PREARCHIVE_CATALOG_FID ON MED_PREARCHIVE_CATALOG_ITEM (FID);

-- FID × 原子条款覆盖行（账本主体，一 FID 多行）。
CREATE TABLE MED_PREARCHIVE_COVERAGE_MAP (
    ID                   VARCHAR2(32) NOT NULL,
    FID                  NUMBER(10) NOT NULL,
    CLAUSE_ID            VARCHAR2(32) NOT NULL,
    METHOD               VARCHAR2(20) NOT NULL,
    COVERAGE             VARCHAR2(10) NOT NULL,
    THRESHOLD_SOURCE     VARCHAR2(255) NOT NULL,
    SEVERITY_SUGGESTION  VARCHAR2(16) NOT NULL,
    REF_SCORE            VARCHAR2(16) NOT NULL,
    STATUS               VARCHAR2(16) NOT NULL,
    CONFIRMED_BY         VARCHAR2(128) NOT NULL,
    CONFIRMED_AT         DATE,
    VERIFIED_AT          DATE,
    RULE_VERSION         VARCHAR2(64) NOT NULL,
    OWNER                VARCHAR2(128) NOT NULL,
    UPDATED_AT           DATE NOT NULL,
    CLAUSE_TEXT          CLOB NOT NULL,
    RULE_IDS_JSON        CLOB NOT NULL,
    COVERED_CLAUSES      CLOB NOT NULL,
    UNCOVERED_CLAUSES    CLOB NOT NULL,
    FIELDS_JSON          CLOB NOT NULL,
    SOURCES_JSON         CLOB NOT NULL,
    BLOCKED_REASON       CLOB NOT NULL,
    EXAMPLE_POSITIVE     CLOB NOT NULL,
    EXAMPLE_NEGATIVE     CLOB NOT NULL,
    LINKED_TESTS_JSON    CLOB NOT NULL,
    NEXT_STEP            CLOB NOT NULL,
    CONSTRAINT UQ_PREARCHIVE_COVERAGE_FID_CLAUSE UNIQUE (FID, CLAUSE_ID),
    CONSTRAINT PK_MED_PREARCHIVE_COVERAGE_MAP PRIMARY KEY (ID)
);
COMMENT ON TABLE MED_PREARCHIVE_COVERAGE_MAP IS '046 覆盖账本：FID→原子条款→判定方式/规则/缺口';
CREATE INDEX IX_PREARCHIVE_COVERAGE_METHOD ON MED_PREARCHIVE_COVERAGE_MAP (METHOD);
CREATE INDEX IX_PA_COVERAGE_FID ON MED_PREARCHIVE_COVERAGE_MAP (FID);

-- 一次检查运行（trigger=轮询/提交/复检/trial；同 anchor 复检=新 revision）。
CREATE TABLE MED_PREARCHIVE_RUN (
    ID                   VARCHAR2(32) NOT NULL,
    RUN_REVISION         NUMBER(10) DEFAULT 1 NOT NULL,
    PATIENT_ID           VARCHAR2(64) NOT NULL,
    VISIT_NUMBER         VARCHAR2(32) NOT NULL,
    DEPT_CODE            VARCHAR2(64) NOT NULL,
    DEPT_NAME            VARCHAR2(128) NOT NULL,
    TRIGGER_TYPE         VARCHAR2(32) NOT NULL,
    TRIGGER_ID           VARCHAR2(128) NOT NULL,
    SUBMISSION_ID        VARCHAR2(128) NOT NULL,
    SNAPSHOT_ID          VARCHAR2(128) NOT NULL,
    RULESET_REVISION     VARCHAR2(64) NOT NULL,
    RULESET_HASH         VARCHAR2(64) NOT NULL,
    IS_TRIAL             NUMBER(10) DEFAULT 0 NOT NULL,
    STATUS               VARCHAR2(16) NOT NULL,
    STATUS_DETAIL        VARCHAR2(512) NOT NULL,
    REQUESTED_BY         VARCHAR2(128) NOT NULL,
    STARTED_AT           DATE,
    FINISHED_AT          DATE,
    CHECKED_AT           DATE,
    DATA_SNAPSHOT_AT     DATE,
    RESULT_ID            NUMBER(10),
    CREATED_AT           DATE NOT NULL,
    UPDATED_AT           DATE NOT NULL,
    SUMMARY_JSON         CLOB NOT NULL,
    SOURCE_HEALTH_JSON   CLOB NOT NULL,
    TRIAL_RULES_JSON     CLOB NOT NULL,
    TRIAL_SCOPE_JSON     CLOB NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_RUN PRIMARY KEY (ID),
    CONSTRAINT UQ_PREARCHIVE_RUN_REVISION UNIQUE (PATIENT_ID, VISIT_NUMBER, RUN_REVISION)
);
COMMENT ON TABLE MED_PREARCHIVE_RUN IS '046 检查运行（含 trial；同就诊复检递增 run_revision）';
CREATE INDEX IX_PREARCHIVE_RUN_TRIAL ON MED_PREARCHIVE_RUN (IS_TRIAL, STATUS);
CREATE INDEX IX_PREARCHIVE_RUN_TRIGGER ON MED_PREARCHIVE_RUN (TRIGGER_TYPE, STATUS);

-- 单规则 × 事件实例评估行（五态 + 排除原因）。
CREATE TABLE MED_PREARCHIVE_RULE_EVAL (
    ID                   VARCHAR2(32) NOT NULL,
    RUN_ID               VARCHAR2(32) NOT NULL,
    RULE_ID              VARCHAR2(128) NOT NULL,
    RULE_VERSION         VARCHAR2(64) NOT NULL,
    EVENT_INSTANCE_ID    VARCHAR2(64) NOT NULL,
    FID                  NUMBER(10),
    CLAUSE_ID            VARCHAR2(32) NOT NULL,
    STATUS               VARCHAR2(20) NOT NULL,
    EXCLUSION_REASON     VARCHAR2(48) NOT NULL,
    REASON_CODE          VARCHAR2(64) NOT NULL,
    OBSERVED_AT          DATE,
    DEADLINE_AT          DATE,
    IS_TRIAL             NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_AT           DATE NOT NULL,
    EVIDENCE_JSON        CLOB NOT NULL,
    CONSTRAINT UQ_PREARCHIVE_EVAL_RUN_RULE_EVENT UNIQUE (RUN_ID, RULE_ID, EVENT_INSTANCE_ID),
    CONSTRAINT PK_MED_PREARCHIVE_RULE_EVAL PRIMARY KEY (ID)
);
COMMENT ON TABLE MED_PREARCHIVE_RULE_EVAL IS '046 逐规则评估（pass/fail/unknown/not_applicable/pending）';
CREATE INDEX IX_PREARCHIVE_EVAL_STATUS ON MED_PREARCHIVE_RULE_EVAL (STATUS);
CREATE INDEX IX_PA_RULE_EVAL_RUN ON MED_PREARCHIVE_RULE_EVAL (RUN_ID);

-- 缺陷实例：同一临床问题生命周期内 issue_id 稳定（复检不换 ID，状态流转）。
CREATE TABLE MED_PREARCHIVE_ISSUE (
    ID                   VARCHAR2(32) NOT NULL,
    ISSUE_KEY            VARCHAR2(128) NOT NULL,
    PATIENT_ID           VARCHAR2(64) NOT NULL,
    VISIT_NUMBER         VARCHAR2(32) NOT NULL,
    DEPT_CODE            VARCHAR2(64) NOT NULL,
    FID                  NUMBER(10),
    CLAUSE_ID            VARCHAR2(32) NOT NULL,
    RULE_ID              VARCHAR2(128) NOT NULL,
    RULE_VERSION         VARCHAR2(64) NOT NULL,
    EVENT_INSTANCE_ID    VARCHAR2(64) NOT NULL,
    SEVERITY             VARCHAR2(16) NOT NULL,
    STATUS               VARCHAR2(24) NOT NULL,
    FIRST_SEEN_RUN_ID    VARCHAR2(32) NOT NULL,
    LAST_SEEN_RUN_ID     VARCHAR2(32) NOT NULL,
    FIRST_SEEN_AT        DATE NOT NULL,
    LAST_SEEN_AT         DATE NOT NULL,
    RESOLVED_RUN_ID      VARCHAR2(32) NOT NULL,
    VERSION              NUMBER(10) DEFAULT 1 NOT NULL,
    IS_TRIAL             NUMBER(10) DEFAULT 0 NOT NULL,
    DELIVERED_EVENT_ID   VARCHAR2(64) NOT NULL,
    CREATED_AT           DATE NOT NULL,
    UPDATED_AT           DATE NOT NULL,
    MESSAGE              CLOB NOT NULL,
    DOCUMENT_REFS_JSON   CLOB NOT NULL,
    CONSTRAINT UQ_PREARCHIVE_ISSUE_KEY UNIQUE (ISSUE_KEY),
    CONSTRAINT PK_MED_PREARCHIVE_ISSUE PRIMARY KEY (ID)
);
COMMENT ON TABLE MED_PREARCHIVE_ISSUE IS '046 缺陷实例（稳定生命周期；人工状态与引擎结论分离）';
CREATE INDEX IX_PREARCHIVE_ISSUE_STATUS ON MED_PREARCHIVE_ISSUE (STATUS);
CREATE INDEX IX_PREARCHIVE_ISSUE_VISIT ON MED_PREARCHIVE_ISSUE (PATIENT_ID, VISIT_NUMBER);
CREATE INDEX IX_PA_ISSUE_PATIENT ON MED_PREARCHIVE_ISSUE (PATIENT_ID);

-- 人工核查动作（append-only：看过/整改/误报/关闭/复检）。
CREATE TABLE MED_PREARCHIVE_ISSUE_ACTION (
    ID                   VARCHAR2(32) NOT NULL,
    ISSUE_ID             VARCHAR2(32) NOT NULL,
    ACTION               VARCHAR2(32) NOT NULL,
    STATUS_FROM          VARCHAR2(24) NOT NULL,
    STATUS_TO            VARCHAR2(24) NOT NULL,
    OPERATOR_ID          VARCHAR2(128) NOT NULL,
    OPERATOR_NAME        VARCHAR2(128) NOT NULL,
    ISSUE_VERSION        NUMBER(10) DEFAULT 0 NOT NULL,
    DOCUMENT_REVISION    VARCHAR2(128) NOT NULL,
    CREATED_AT           DATE NOT NULL,
    REASON               CLOB NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_ISSUE_ACTION PRIMARY KEY (ID)
);
COMMENT ON TABLE MED_PREARCHIVE_ISSUE_ACTION IS '046 人工核查动作（append-only 审计）';
CREATE INDEX IX_PA_ISSUE_ACTION_TIME ON MED_PREARCHIVE_ISSUE_ACTION (CREATED_AT);
CREATE INDEX IX_PA_ISSUE_ACTION_ISSUE ON MED_PREARCHIVE_ISSUE_ACTION (ISSUE_ID);

-- AI 匹配任务（批量 92/选中 FID → 候选）。
CREATE TABLE MED_PREARCHIVE_MATCH_TASK (
    ID                   VARCHAR2(32) NOT NULL,
    STATUS               VARCHAR2(16) NOT NULL,
    INPUT_HASH           VARCHAR2(64) NOT NULL,
    MODEL_NAME           VARCHAR2(128) NOT NULL,
    PROMPT_VERSION       VARCHAR2(32) NOT NULL,
    PROGRESS_DONE        NUMBER(10) DEFAULT 0 NOT NULL,
    PROGRESS_TOTAL       NUMBER(10) DEFAULT 0 NOT NULL,
    DURATION_MS          NUMBER(10) DEFAULT 0 NOT NULL,
    ATTEMPTS             NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_BY           VARCHAR2(128) NOT NULL,
    CREATED_AT           DATE NOT NULL,
    UPDATED_AT           DATE NOT NULL,
    FID_FILTER_JSON      CLOB NOT NULL,
    MODEL_CONFIG_JSON    CLOB NOT NULL,
    PROCESSED_FIDS_JSON  CLOB NOT NULL,
    FAILED_FIDS_JSON     CLOB NOT NULL,
    ERROR                CLOB NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_MATCH_TASK PRIMARY KEY (ID)
);
COMMENT ON TABLE MED_PREARCHIVE_MATCH_TASK IS '046 AI 匹配任务（分批/可取消/断点恢复/费用可查）';
CREATE INDEX IX_PREARCHIVE_MATCH_STATUS ON MED_PREARCHIVE_MATCH_TASK (STATUS);

-- AI 匹配候选（含确定性校验结果与用户接受/驳回）。
CREATE TABLE MED_PREARCHIVE_MATCH_CANDIDATE (
    ID                   VARCHAR2(32) NOT NULL,
    TASK_ID              VARCHAR2(32) NOT NULL,
    FID                  NUMBER(10) NOT NULL,
    CLAUSE_ID            VARCHAR2(32) NOT NULL,
    CONFIDENCE           VARCHAR2(16) NOT NULL,
    VALIDATION_OK        NUMBER(10) DEFAULT 0 NOT NULL,
    DECISION             VARCHAR2(16) NOT NULL,
    DECIDED_BY           VARCHAR2(128) NOT NULL,
    DECIDED_AT           DATE,
    EXACT_MATCH          NUMBER(10) DEFAULT 0 NOT NULL,
    CREATED_AT           DATE NOT NULL,
    MATCHED_RULE_IDS_JSON CLOB NOT NULL,
    SUGGESTED_DSL_JSON   CLOB NOT NULL,
    FIELD_REFS_JSON      CLOB NOT NULL,
    COVERED_CLAUSES      CLOB NOT NULL,
    UNCOVERED_CLAUSES    CLOB NOT NULL,
    RATIONALE            CLOB NOT NULL,
    BLOCKING_REASONS_JSON CLOB NOT NULL,
    VALIDATION_ERRORS_JSON CLOB NOT NULL,
    DECIDED_NOTE         CLOB NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_MATCH_CANDIDATE PRIMARY KEY (ID)
);
COMMENT ON TABLE MED_PREARCHIVE_MATCH_CANDIDATE IS '046 AI 匹配候选（校验不通过不得发布；用户接受/驳回留痕）';
CREATE INDEX IX_PREARCHIVE_MATCH_CAND_FID ON MED_PREARCHIVE_MATCH_CANDIDATE (FID, DECISION);
CREATE INDEX IX_PA_MATCH_CAND_TASK ON MED_PREARCHIVE_MATCH_CANDIDATE (TASK_ID);

-- trial 观察反馈（确认缺陷/误报/待核实——人工结论与引擎结论分开）。
CREATE TABLE MED_PREARCHIVE_TRIAL_FEEDBACK (
    ID                   VARCHAR2(32) NOT NULL,
    RUN_ID               VARCHAR2(32) NOT NULL,
    RULE_ID              VARCHAR2(128) NOT NULL,
    EVENT_INSTANCE_ID    VARCHAR2(64) NOT NULL,
    FID                  NUMBER(10),
    VERDICT              VARCHAR2(24) NOT NULL,
    OPERATOR_ID          VARCHAR2(128) NOT NULL,
    OPERATOR_NAME        VARCHAR2(128) NOT NULL,
    CREATED_AT           DATE NOT NULL,
    NOTE                 CLOB NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_TRIAL_FEEDBACK PRIMARY KEY (ID),
    CONSTRAINT UQ_PREARCHIVE_TRIAL_FEEDBACK UNIQUE (RUN_ID, RULE_ID, EVENT_INSTANCE_ID, OPERATOR_ID)
);
COMMENT ON TABLE MED_PREARCHIVE_TRIAL_FEEDBACK IS '046 trial 观察反馈（不改变引擎结论；确认后才转正式）';
CREATE INDEX IX_PA_TRIAL_FEED_VERDICT ON MED_PREARCHIVE_TRIAL_FEEDBACK (VERDICT);
CREATE INDEX IX_PA_TRIAL_FEEDBACK_RUN ON MED_PREARCHIVE_TRIAL_FEEDBACK (RUN_ID);

-- JHEMR 详情票据 nonce（短期一次性；防重放）。
CREATE TABLE MED_PREARCHIVE_VIEW_TICKET (
    ID                   VARCHAR2(32) NOT NULL,
    NONCE                VARCHAR2(128) NOT NULL,
    PATIENT_ID           VARCHAR2(64) NOT NULL,
    VISIT_NUMBER         VARCHAR2(32) NOT NULL,
    OPERATOR_ID          VARCHAR2(128) NOT NULL,
    DEPT_CODE            VARCHAR2(64) NOT NULL,
    SCOPE                VARCHAR2(64) NOT NULL,
    EXPIRES_AT           DATE NOT NULL,
    USED_AT              DATE,
    ISSUED_BY            VARCHAR2(128) NOT NULL,
    CREATED_AT           DATE NOT NULL,
    CONSTRAINT PK_MED_PREARCHIVE_VIEW_TICKET PRIMARY KEY (ID),
    CONSTRAINT UQ_PREARCHIVE_VIEW_TICKET_NONCE UNIQUE (NONCE)
);
COMMENT ON TABLE MED_PREARCHIVE_VIEW_TICKET IS '046 JHEMR 一次性详情票据（nonce 重放防护）';
CREATE INDEX IX_PREARCHIVE_TICKET_EXPIRE ON MED_PREARCHIVE_VIEW_TICKET (EXPIRES_AT);

-- ==== MED_PREARCHIVE_RESULT 046 F06 additive 4 列（历史行 NULL=未保存评估明细，不补造） ====
ALTER TABLE MED_PREARCHIVE_RESULT ADD (
    EVALUATIONS_JSON   CLOB,
    NOTICES_JSON       CLOB,
    SOURCE_HEALTH_JSON CLOB,
    SUMMARY_JSON       CLOB
);
-- 2026-09-23 054升级：8 个超30字节索引名缩为 IX_PA_*（Oracle 11.2 ORA-00972；索引名变更不影响功能）
