-- 039 规则中心六表反向清理脚本（回滚参考）。
-- 生产回滚优先：停开关 / 回镜像；本脚本仅在确认六表无有效数据后由 DBA 手工执行。
-- 注意：RULE_AUDIT 与 DELIVERY_LOG 是审计数据，删除前必须留存备份（039 §15 禁止自动删审计）。

DROP TABLE MED_PREARCHIVE_DELIVERY_LOG;
DROP TABLE MED_PREARCHIVE_OUTBOX;
DROP TABLE MED_PREARCHIVE_DESTINATION;
DROP TABLE MED_PREARCHIVE_RULE_AUDIT;
DROP TABLE MED_PREARCHIVE_RULE_POINTER;
DROP TABLE MED_PREARCHIVE_RULE_VERSION;
